version: '3.4'

services:
  authorize:
    container_name: "authorize"
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
     - $API_PORT:80
    environment: 
     - ASPNETCORE_ENVIRONMENT=Production